# Generated by Django 5.1.7 on 2025-03-18 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='taking_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
